// Vendors the site's web fonts into web/fonts/ and writes web/fonts.css from
// the installed @fontsource packages (all OFL-1.1), so the published page makes
// no third-party request at runtime. Latin and latin-ext subsets only. The
// generated rules declare the real family names that styles.css already uses,
// never the packages' "… Variable" aliases.
// Run `npm ci` first, then `node scripts/build_fonts.mjs` after changing FACES
// or bumping a font package. `--check` rebuilds in memory instead of writing
// and fails when the committed web/fonts.css or any file under web/fonts/ no
// longer matches what the installed packages would produce.
import { existsSync, mkdirSync, readdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const outDir = join(root, "web", "fonts");
const cssPath = join(root, "web", "fonts.css");
const SUBSETS = ["latin", "latin-ext"];

// `variants` name the woff2 files the package ships, `<subset>-<variant>.woff2`;
// `css` names the package stylesheet whose @font-face block carries that
// variant's weight range, stretch range, and unicode range.
const FACES = [
  { family: "Bricolage Grotesque", pkg: "@fontsource-variable/bricolage-grotesque", slug: "bricolage-grotesque", variants: ["standard-normal"], css: () => "standard.css" },
  { family: "IBM Plex Sans", pkg: "@fontsource/ibm-plex-sans", slug: "ibm-plex-sans", variants: ["400-normal", "500-normal", "600-normal"], css: variant => `${variant.split("-")[0]}.css` },
  { family: "JetBrains Mono", pkg: "@fontsource-variable/jetbrains-mono", slug: "jetbrains-mono", variants: ["wght-normal"], css: () => "wght.css" },
];

function packageDir(name) {
  const dir = join(root, "node_modules", name);
  if (!existsSync(dir)) throw new Error(`${name} is not installed; run npm ci first`);
  return dir;
}

function faceBlock(cssText, fileStem) {
  const match = cssText.match(new RegExp(`/\\* ${fileStem} \\*/\\s*@font-face \\{([^}]*)\\}`));
  if (!match) throw new Error(`no @font-face block for ${fileStem}`);
  const declarations = Object.fromEntries(match[1].trim().split(";").map(line => line.trim()).filter(Boolean).map(line => {
    const colon = line.indexOf(":");
    return [line.slice(0, colon).trim(), line.slice(colon + 1).trim()];
  }));
  const format = declarations.src.match(/format\('([^']+)'\)/)[1];
  return { weight: declarations["font-weight"], stretch: declarations["font-stretch"], style: declarations["font-style"], range: declarations["unicode-range"], format };
}

function build() {
  const files = new Map();
  const rules = [];
  const versions = [];
  for (const face of FACES) {
    const dir = packageDir(face.pkg);
    const manifest = JSON.parse(readFileSync(join(dir, "package.json"), "utf8"));
    versions.push(`${face.pkg}@${manifest.version} (${manifest.license})`);
    files.set(`${face.slug}-LICENSE.txt`, readFileSync(join(dir, "LICENSE")));
    for (const variant of face.variants) {
      const cssText = readFileSync(join(dir, face.css(variant)), "utf8");
      for (const subset of SUBSETS) {
        const stem = `${face.slug}-${subset}-${variant}`;
        const block = faceBlock(cssText, stem);
        files.set(`${stem}.woff2`, readFileSync(join(dir, "files", `${stem}.woff2`)));
        rules.push([
          `/* ${stem} */`,
          "@font-face {",
          `  font-family: "${face.family}";`,
          `  font-style: ${block.style};`,
          "  font-display: swap;",
          `  font-weight: ${block.weight};`,
          block.stretch ? `  font-stretch: ${block.stretch};` : null,
          `  src: url("fonts/${stem}.woff2") format("${block.format}");`,
          `  unicode-range: ${block.range};`,
          "}",
        ].filter(Boolean).join("\n"));
      }
    }
  }
  const css = `/* Generated by scripts/build_fonts.mjs — do not edit. Sources: ${versions.join(", ")}. */\n\n${rules.join("\n\n")}\n`;
  return { css, files };
}

const { css, files } = build();

if (process.argv.includes("--check")) {
  const problems = [];
  if (!existsSync(cssPath) || readFileSync(cssPath, "utf8") !== css) problems.push("web/fonts.css is stale");
  for (const [name, body] of files) {
    const target = join(outDir, name);
    if (!existsSync(target) || !readFileSync(target).equals(body)) problems.push(`web/fonts/${name} is missing or stale`);
  }
  for (const name of existsSync(outDir) ? readdirSync(outDir) : []) {
    if (!files.has(name)) problems.push(`web/fonts/${name} is not produced by FACES`);
  }
  if (problems.length) {
    console.error(problems.join("\n"));
    console.error("Run `node scripts/build_fonts.mjs` and commit the result.");
    process.exit(1);
  }
  console.log(`web/fonts.css and ${files.size} vendored font files are up to date.`);
} else {
  rmSync(outDir, { recursive: true, force: true });
  mkdirSync(outDir, { recursive: true });
  for (const [name, body] of files) writeFileSync(join(outDir, name), body);
  writeFileSync(cssPath, css);
  console.log(`Wrote web/fonts.css and ${files.size} files to web/fonts/.`);
}
